//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_FUNCTION
    {
        public string FN_CODE { get; set; }
        public string FN_DESC { get; set; }
        public Nullable<bool> FN_SINGLE_ACCESS { get; set; }
        public string FN_USER_ID { get; set; }
        public string FN_FILE_LOCATION { get; set; }
        public string FN_ICON { get; set; }
        public Nullable<int> FN_SEQ { get; set; }
        public Nullable<bool> FN_MULTIWINDOW { get; set; }
        public Nullable<bool> FN_WITH_API { get; set; }
    }
}
