//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_FUN_API
    {
        public string AFA_FUN_FILE { get; set; }
        public string AFA_API_CODE { get; set; }
        public byte APA_SEQ { get; set; }
        public System.DateTime APA_CREATE_DATE { get; set; }
    }
}
