//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySchoolEntities : DbContext
    {
        public MySchoolEntities()
            : base("name=MySchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AP_FUN_API> AP_FUN_API { get; set; }
        public virtual DbSet<AP_FUNCTION> AP_FUNCTION { get; set; }
        public virtual DbSet<AP_STATUS> AP_STATUS { get; set; }
        public virtual DbSet<ImageStore> ImageStore { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<TableB> TableB { get; set; }
    }
}
