//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
        public string s_state { get; set; }
        public string s_type { get; set; }
        public Nullable<System.DateTime> s_date { get; set; }
        public Nullable<int> sss { get; set; }
    }
}
